### PR TITLE
Modal

### PR DESCRIPTION
**Pull request by omjadhav85**
added Modal Component

image
image

### CODE REVIEW

**Comment by omjadhav85** [comment]
Files to be reviewed are only modal.css and modal.html

**Review by adith-a-danthi — APPROVED** [review]
Clean, well-structured code. Good use of semantic HTML tags. Good to merge

**Review by kedark152 — APPROVED** [review]
Clean code. code written very well.

**Comment by omjadhav85** [comment]
Hey! Thanks for reviewing my PR! Merging after two reviews

**Pull request merged**
